apiVersion: v1
kind: Service
metadata:
  name: car-price-service
spec:
  selector:
    app: car-price-predictor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
